openshift/cluster-api-actuator-pkg

- pkg/e2e/framework/framework.go
- pkg/e2e/framework/machines.go
> Parametrize ssh user

- Makefile
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/yaml-lint.sh
CI implementation is in https://github.com/openshift/release/pull/1887
> add tooling for CI

- pkg/e2e/framework/clusterapi.go
- pkg/e2e/framework/clusters.go
- pkg/e2e/framework/framework.go
- pkg/e2e/framework/machines.go
- pkg/e2e/framework/ssh.go
- pkg/manifests/manifests.go
- pkg/manifests/userdata.go
- reuse the framework among actuators
- reuse the framework for cluster API bootstrapping
> Make e2e framework reusable outside of e2e

- OWNERS
> More owners

- Makefile
> remove copyright notice

- Makefile
- pkg/e2e/framework/machines.go
- pkg/manifests/manifests.go
> Fix fmt script invocation

- pkg/manifests/manifests.go
> Logrus to glog

- pkg/manifests/manifests.go
Include `Status` as a subresource in machine object
> Fix machine crd

- pkg/manifests/manifests.go
Allow to work with CRD subresource as well.
> Extend RBAC role with updating status subresource

- pkg/e2e/framework/clusterapi.go
- pkg/manifests/manifests.go
Drop the StatefulSet in favor of one deployment that carries all the machine API controllers.
> Deploy manager controller with machine controller

- pkg/e2e/infra/infra.go
- pkg/e2e/infra/utils.go
> Scaling stories

- pkg/e2e/README.md
Update readme implementation details
> Update readme implementation details

- pkg/e2e/infra/infra.go
NOTE: This will fail in minikube until I push new kubemark-controllers image. Need to run few additional checks to make sure it's not breaking stuff.
/hold
> Verify any invalid machineset is refused

- pkg/manifests/manifests.go
To unblock https://github.com/openshift/cluster-api-provider-aws/pull/203
> Rename sigs.k8s.io prefixed labels to machine.openshift.io prefixed labels

- pkg/e2e/autoscaler/autoscaler.go
This PR is extending existing autoscaler e2e tests. Existing e2e test uses just one machineAutoscalerGroup(machineset). This PR is modifying the test to use two machineAutoscalerGroups and test is being extended to verify that a particular machineAutoscalerGroup is not scaling beyond configured max nodes.
> Extend autoscaler test with multiple machineAutoscalerResource

- pkg/e2e/autoscaler/autoscaler.go
The previous behaviour was to scale out by waiting for the expected
scale up events to be generated on the node groups. After that had
completed we then waited for a further 60s to ensure that there were
no further scale up attempts as we had explicitly capped the cluster
size.
This commit changes the behaviour from waiting for 60s to explicitly
waiting for the MaxNodesTotalReached event to be generated as well. We use
that event to assert that the cluster will not grow beyond the
specified maximum.
This PR also helps to validate that we carry two upstream fixes that
were made with respect to calculating when the maximum size of the
cluster is reached:
- https://github.com/kubernetes/autoscaler/pull/1516
- https://github.com/kubernetes/autoscaler/pull/1771
> e2e/autoscaler: consume MaxNodesTotalReached event

- pkg/e2e/autoscaler/autoscaler.go
- pkg/e2e/framework/framework.go
https://jira.coreos.com/browse/CLOUD-537
> Dump autoscaler logs before deleting the resource

- README.md
Add broad instructions for running the cluster autoscaler e2e tests using a local minikube cluster.
> README: Add instructions for running autoscaler tests under minikube

- pkg/e2e/autoscaler/autoscaler.go
Rather than guess at the number of jobs to create--which triggers the
scale up---we now compute that value dynamically.
The computation is based on the number of nodes in the cluster and to
ensure that one we only get one pod per node the memory requirement is
set at 70% of a node's overall memory capacity.
The motivation for this change is to reduce the overall number of
events generated. As this test explicitly requires explicit events to
be generated--and consumed--we now stand a better chance of not having
critical events (for the test) dropped.
When test runs we now see a limited set of events related to scale-up:
```console
cluster-autoscaler-status: Scale-up: setting group openshift-machine-api/amcdermo-st695-worker-us-east-2a size to 2
cluster-autoscaler-status: Max total nodes in …
```
> e2e/autoscaler: dynamically compute workload size

- pkg/e2e/infra/utils.go
This is to aid debugging as we expand the e2e suite to Azure and GCP.
> e2e/infra: print time remaining in PollImmediate calls

- pkg/e2e/infra/infra.go
This is to ensure that the RC's pods get deleted.
> Use a cascading delete in drain test cleanup

- pkg/e2e/autoscaler/autoscaler.go
The autoscaler test now creates its own machinesets Ahead-Of-Time
rather than relying on what is available on the cluster.
The intent is for the test to be more resilient to other tests failing
in the e2e suite which typically leave nodes/machines hanging around
and that perturbs the expectations for scale out (i.e., we end up with
$N more nodes that are eligible for scheduling than expected).
> e2e/autoscaler: create all machinesets AOT

- pkg/e2e/infra/utils.go
Sometimes this will timeout because Status.Replicas !=
Status.ReadyReplicas. Print the state of all the pods for debugging
purposes so we can distinguish between the cases when it works and
those rarer cases when it doesn't.
> e2e/infra: dump POD status in waitUntilAllRCPodsAreReady

- pkg/e2e/autoscaler/autoscaler.go
Retry fetching the MachineSet after scale down has occurred. This is
to mitigate against the following flake:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-openshift-cluster-autoscaler-operator-e2e-azure-master/219/
```console
• Failure [504.320 seconds]
[Feature:Machines] Autoscaler should
/tmp/tmp.dpTJIRSLMU/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go:231
scale up and down [It]
/tmp/tmp.dpTJIRSLMU/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go:232
Unexpected error:
<*errors.StatusError | 0xc420a44b40>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
Status: "Failure",
Message: "Operation cannot be fulfilled on …
```
> e2e/autoscaler: add retry on conflict post scale down

- pkg/e2e/autoscaler/autoscaler.go
We see occasional flakes in CI[1] where the test doesn't complete because we
don't match the original machine count. This commit now waits for all
PODS in the workload to disappear (and the presence of these can
trigger further scale-ups) and then deletes the cluster-autoscaler
before scaling all the transient machinesets to zero. The intent is to
remove those resources that would allow a new machine/node to be
created.
The failure in CI looks like:
```
I0903 07:23:09.559723    7043 autoscaler.go:467] [1s remaining] Waiting for cluster to reach original machine count of 6; currently have 7
• Failure [1576.431 seconds]
[Feature:Machines] Autoscaler should
/tmp/tmp.TLbP279CTf/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go:232
scale up and down [It] …
```
> e2e/autoscaler: prevent scale up after workload has been deleted

- Dockerfile
I don't think we need this after all.
> Remove unnecessary Dockerfile

- pkg/e2e/framework/common.go
- pkg/e2e/infra/infra.go
Adding random ID to machine names in infra tests.
> Add a random ID to machine names in infra tests

- Makefile
- go.mod
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
Bump scripts and docker images to Go 1.13
> [OCPCLOUD-813] Bump scripts to Go 1.13

- Makefile
- hack/ci-integration.sh
- pkg/autoscaler/autoscaler.go
- pkg/framework/clusterautoscalers.go
- pkg/framework/machinesets.go
- pkg/infra/infra.go
This is a continuation of #140, it adds tests for the autoscaler to exercise scaling from and to zero nodes.
> Bug 1827657: Validate scale from/to zero

- pkg/framework/deployment.go
- pkg/operators/cluster-autoscaler-operator.go
- pkg/operators/cluster-machine-approver.go
- pkg/operators/machine-api-operator.go
Since we added support for the machine approver cluster operator, we want to validate it works as expected.
https://github.com/openshift/cluster-machine-approver/pull/71
> Bug 1834723: Add e2e validation for cluster machine approver cluster operator status

- pkg/framework/deployment.go
- pkg/framework/framework.go
- pkg/framework/machines.go
- pkg/framework/nodes.go
- pkg/operators/machine-api-operator.go
Adds check for `deployment.spec` update after deletion.
> OCPCLOUD-867 - Add MAO e2e for validating the deployment is resynced

- pkg/framework/framework.go
- pkg/framework/machines.go
- pkg/framework/machinesets.go
- pkg/machinehealthcheck/machinehealthcheck.go
OCPCLOUD-874 - Implement a validation for MHC maxUnhealthy
> MHC check to respect maxUnhealthy value

- pkg/infra/infra.go
Because https://github.com/openshift/machine-api-operator/pull/615 is adding webhook validation that will take over the responsibility for rejecting invalid MachineSets from the controller, the test is currently failing for that branch.
This updates the test to allow the error to be nil (`Not(HaveOccurred())`) as was the existing behaviour, or to `MatchError` with the string `"admission webhook \"default.machineset.machine.openshift.io\" denied the request: providerSpec.value: Required value: a value must be provided"`
We use [MatchError](https://onsi.github.io/gomega/#matcherrorexpected-interface) because it will compare `err.Error()` to the string given, and we use the particular string because this is the error coming out of the test currently (see …
> Allow webhook to reject invalid MachineSets

- pkg/autoscaler/autoscaler.go
This change adds a test to the autoscale "scale up and down" suite that
will check to see if there are any deletion taints left on the node
resources after a scale down.
This test is related to bugzilla case 1823667 . reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1823667
> add a test for deletion taints after scale down

- pkg/infra/infra.go
Once MachineSet webhook validation is introduced, this test should rely on the webhook validation rather than controller validation to detect invalid MachineSets 
Validation coming from: https://github.com/openshift/machine-api-operator/pull/615
> Make invalid machineset test rely on webhook instead of controller

- pkg/autoscaler/autoscaler.go
This change replaces the old test with a new version. This is being done
to move away from the event based testing of the previous version
towards an observation based test. What this means is that instead of
watching for scaling events the test will now observe the sizes of
MachineSet resources to determine scaling activity.
> rewrite scale up and down test for autoscaler

- Makefile
- go.mod
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
- vendor/modules.txt
Unblocks https://github.com/openshift/release/pull/13785
> [OCPCLOUD-977] Bump scripts to Go 1.15

- pkg/e2e_test.go
Co-Authored-By: Martin André <maandre@redhat.com>
> openstack: Increase timeouts

- Dockerfile.ci
- Makefile
- go.mod
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
This commit sets the minimal golang version for the project to 1.16.
> Upgrade to use golang 1.16

- OWNERS
> add lobziik and fedosin to owners

- pkg/framework/machinesets.go
> Fix formatting

- pkg/infra/infra.go
- pkg/infra/lifecyclehooks.go
- pkg/infra/spot.go
- pkg/infra/webhooks.go
This change adds exception text to the gomega assertions in the infra test suite so that we can more easily detect where failures are occurring.
> OCPCLOUD-1714: Add exception annotations to infra tests

- pkg/machinehealthcheck/machinehealthcheck.go
This PR annotates all the `Expect` block with exceptions so we can easily trace bugs in the test suite.
> [OCPCLOUD-1715]: Add exception annotations to mhc tests

- pkg/autoscaler/autoscaler.go
this change adds a bunch of exception text to the gomega assertions in the autoscaler test suite so that we can more easily detect where failures are occurring.
> OCPCLOUD-1712: add exception annotations to autoscaler tests

- testutils/resourcebuilder/core/v1/node.go
To be able to create nodes with various conditions (more notably Ready/NotReady).
> resourcebuilder: node: add conditions support

- pkg/autoscaler/autoscaler.go
The autoscaler tests were removing UUID label from the machines to allow them to balance properly when scaling. I've changed that to use the new BalancingIgnoredLabels CRD option to tests it.
> OCPCLOUD-1427: Use BalancingIgnoredLabels in autoscaler test

- pkg/autoscaler/autoscaler.go
this change adds a 60 second sleep to the balance similar nodes test so that the new nodes have proper time to acquire their capacity resources, and so that the autoscaler has time to update its records. through experimentation, it appears that 60 seconds is sufficient time for the autoscaler to become aware of the changes. ideally this will be remediated in the future, but for now this change is being proposed to help the stability of this test.
> OCPBUGS-14289: add a sleep to balance similar nodes test

- pkg/providers/aws.go
This is a PR for [OCPCLOUD-1717](https://issues.redhat.com/browse/OCPCLOUD-1717) to add annotations to error outputs in the AWS E2E tests to make debugging easier.
> OCPCLOUD-1717: Add annotations to error output

- pkg/autoscaler/autoscaler.go
Manual backport of https://github.com/openshift/cluster-api-actuator-pkg/pull/317 and https://github.com/openshift/cluster-api-actuator-pkg/pull/318.
> OCPBUGS-35739: Fix ScaleFromZero tests

- pkg/autoscaler/autoscaler.go
- pkg/framework/machinesets.go
This should allow for different type of topology, including compact clusters.
> OCPBUGS-35745: Do not assume the number of nodes

- testutils/resourcebuilder/machine/v1beta1/machine.go
Add the ability to specify the providerID for a Machine.
> testutils: resourcebuilder: machine add providerID

- Makefile
- pkg/autoscaler/autoscaler.go
- pkg/framework/ginkgo-labels.go
- pkg/infra/infra.go
- pkg/infra/lifecyclehooks.go
- pkg/infra/spot.go
- pkg/infra/webhooks.go
- pkg/machinehealthcheck/machinehealthcheck.go
- pkg/operators/cluster-autoscaler-operator.go
- pkg/operators/cluster-machine-approver.go
- pkg/operators/machine-api-operator.go
- pkg/providers/aws.go
Manually cherry-pick of https://github.com/openshift/cluster-api-actuator-pkg/pull/344
@JoelSpeed PTAL
> [release-4.17] OCPQE-26161,OCPBUGS-47522: update labels based on label proposal

- pkg/framework/aws_client.go
- pkg/providers/aws.go
As the [ticket](https://issues.redhat.com/browse/DPP-16032) solved, so enable capacityReservation case.
also update it to reserve the capacity with an end date to ensure the resources will be expire after 35 minutes to save cost even when the case failed.
and also update to use the common AwsClient function. @sunzhaohua2 @miyadav @shellyyang1989 @JoelSpeed PTAL, thanks!
Run in local passed:
```
liuhuali@Lius-MacBook-Pro cluster-api-actuator-pkg % ./hack/ci-integration.sh -focus "CapacityReservationID" -v
Running Suite: Machine Suite - /Users/liuhuali/project/cluster-api-actuator-pkg/pkg
===================================================================================
Random Seed: 1734938414
Will run 2 of 45 specs
[BeforeSuite] …
```
> OCPQE-27801: enable capacityReservation case

- Makefile
- pkg/autoscaler/autoscaler.go
- pkg/framework/ginkgo-labels.go
- pkg/infra/infra.go
- pkg/infra/lifecyclehooks.go
- pkg/infra/spot.go
- pkg/infra/webhooks.go
- pkg/machinehealthcheck/machinehealthcheck.go
- pkg/operators/cluster-autoscaler-operator.go
- pkg/operators/cluster-machine-approver.go
- pkg/operators/machine-api-operator.go
- pkg/providers/aws.go
Manually cherry-pick of https://github.com/openshift/cluster-api-actuator-pkg/pull/352
> [release-4.13] OCPQE-26161,OCPBUGS-47632: update labels based on label proposal

- .ci-operator.yaml
- pipeline/handleresult.py
Manually cherry-pick of https://github.com/openshift/cluster-api-actuator-pkg/pull/360
> [release-4.12] OCPBUGS-47544: add python script to handle test result so that can show in report portal

- hack/ci-integration.sh
- pkg/framework/framework.go
- pkg/framework/machinesets.go
- pkg/infra/spot.go
- pkg/infra/webhooks.go
Manually cherry-pick https://github.com/openshift/cluster-api-actuator-pkg/pull/374
> [release-4.17] NO-JIRA:Fix the failures in qe ci jobs

- pkg/capi/gcp.go
@huali9 @sunzhaohua2 @shellyyang1989 PTAL when time permits.
> OCPQE-28645: exclude test for multiarch or arm64 clusters

- pkg/framework/capi_machinesets.go
> NO-JIRA: Update capi machineset labels

- pkg/infra/spot.go
We are adding network policy in 4.20, which causes this spot case failed. So I update it as Joel suggested https://github.com/openshift/machine-api-operator/pull/1387#issuecomment-3083611620
I tested this on the cluster with [my pr](https://github.com/openshift/machine-api-operator/pull/1387) and the cluster without my pr, both works. @JoelSpeed PTAL, thanks!
```
liuhuali@Lius-MacBook-Pro cluster-api-actuator-pkg % ./hack/ci-integration.sh -focus "should handle the spot instances" -v
Running Suite: Machine Suite - /Users/liuhuali/project/cluster-api-actuator-pkg/pkg
===================================================================================
Random Seed: 1752807997
Will run 1 of 66 specs
[BeforeSuite] …
```
> OCPCLOUD-2980: update spot case to add network policy

- pkg/operators/machine-api-operator.go
Regression jobs passed but failed on the post phase, collect must-gather failed errors occurred while gathering container data.
[kube-apiserver ](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-api-provider-azure/160/pull-ci-openshift-machine-api-provider-azure-main-regression-clusterinfra-azure-ipi-mapi-2of3/1947975214709084160/artifacts/regression-clusterinfra-azure-ipi-mapi/gather-extra/artifacts/oc_cmds/clusteroperators)in PROGRESSING status, [2 nodes](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-api-provider-azure/160/pull-ci-openshift-machine-api-provider-azure-main-regression-clusterinfra-azure-ipi-mapi-2of3/1947975214709084160/artifacts/regression-clusterinfr …
> check cluster operators again to make sure cluster is recovered
