pkg/e2e/framework/clusterapi.go
pkg/e2e/framework/framework.go
pkg/e2e/framework/machines.go

- list clusters before claiming cluster API is deployed
- increase timeouts
- add libvirt specific flags
- delete machines/machinesets in reverse order

Minor updates

---

pkg/e2e/framework/clusterapi.go
pkg/manifests/manifests.go

Leftover after the migration to CRD based cluster-api. Not affecting AWS, only libvirt.

Pass libvirt PK to the machine controller

---

pkg/manifests/manifests.go

For machineset, machinedeployment and cluster
https://github.com/openshift/machine-api-operator/blob/master/owned-manifests/cluster.crd.yaml#L14-L15 a similar.
Follow up of https://github.com/openshift/cluster-api-actuator-pkg/pull/16

Add missing subresource to CRDs

---

pkg/manifests/manifests.go

The machine controller reads a user data from a secret.
Thus, the pod running the machine controller must be allowed to list secrets.
/hold
until verified in https://github.com/openshift/cluster-api-provider-libvirt/pull/92

Allow the machine-role clusterrole to list secrest as well

---

pkg/e2e/framework/machines.go
pkg/types/types.go

So it can be imported by other packages without running e2e framework initiliation (`init()`).

Move CloudProviderClient under separate package

---

pkg/e2e/autoscaler/autoscaler.go

To be able to count how many machines are in a node group
and how many nodes are actually linked. Autoscaling scale out
is failing either due to a node taking too much time to register
or for node labels not being properly propagated from machines.

[autoscaling]: print which machines actually reference a node

---

pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go

Abstract function for 'have machines resources backing nodes' story
Enforce same number of nodes and machines Fixed by https://github.com/openshift/cluster-api-actuator-pkg/pull/41/commits/3ed9405d07fc4403103ab822ea7b6b61bb4f4091

Abstract function for 'have machines resources backing nodes' story

---

pkg/e2e/operators/machine-api-operator.go
pkg/e2e/operators/utils.go

Refactor deployments for operators continuing with the pattern:
- modeling dsl for manipulating objects
- Ginkgo consumes it and just make aotmic/eventually assertions

Refactor deployments for operators

---

pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go

[Feature:Machines] Managed cluster should - have ability to additively reconcile taints from machine to nodes
- Add nodes snapshot
- Update test to rely on emerging DSL api
- Ensure original taints are restored at the end of the test
Goes after https://github.com/openshift/cluster-api-actuator-pkg/pull/43

Improve Taints validation

---

pkg/e2e/autoscaler/autoscaler.go

The presence of this field was (always) causing the test to fail, or
at best be very flaky. The value specified in the job was 100s.
The autoscaler tests would start, the replica count would get bumped,
we would wait for the machine to become a node, but 100s would elapse
and (quoting from the docs):
The ActiveDeadlineSeconds applies to the duration of the job, no
matter how many Pods are created. Once a Job reaches
activeDeadlineSeconds, all of its Pods are terminated and the Job
status will become type: Failed with reason: DeadlineExceeded.
the job that triggered scale up would disappear (because
DeadlineExceeded).
At the next cluster-autoscaler scan interval (every 10s) the CA would
notice that there wasn't a need for the node it just created as there
are "No unschedulable pods". This …

e2e/autoscaler: remove ActiveDeadlineSeconds from job definition

---

pkg/e2e/autoscaler/autoscaler.go

The purpose of the workload is to start enough pods that triggers the
cluster autoscaler to start scaling up. We don't ever want those pods
to complete - their purpose is to run effectively indefinitely. The
current timeout is 300s. I'm deliberately making this a much larger
value (1 day) so that the pods have no chance to run to completion.

e2e/autoscaler: Bump autoscaler workload timeout

---

Makefile
pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/framework/common.go
pkg/e2e/framework/framework.go
pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go
pkg/e2e/machinehealthcheck/machinehealthcheck.go

- simplifying the code
- making the code more readable

Code improvements

---

pkg/manifests/userdata.go

K8s version requires kubernetes-cni to be fixed to 0.6.0.
Though, kubernetes repo provides higher version that is not
met by the constraint. Thus, failing to install k8s rpms.

Bump k8s version and pin kubernetes-cni version

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/framework/common.go
pkg/e2e/framework/machinehealthcheck.go
pkg/e2e/framework/machines.go
pkg/e2e/framework/nodes.go
pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go
pkg/e2e/machinehealthcheck/machinehealthcheck.go

- move setup logic to separate methods
- add TODO on the kubemark skip condition

Refactor machine-health-check tests

---

pkg/e2e/operators/utils.go

Sometimes a clusterapi-manager-controllres-XXXX pod stucks in Terminated
state before a deployment is allowed to be created again. Thus, it takes
longer than 1 minute for a deleted deployment to be re-created by
the machine api operator.

Wait longer for clusterapi-manager-controllers deployment do re-appear

---

pkg/e2e/framework/framework.go
pkg/e2e/machinehealthcheck/machinehealthcheck.go

Occasionally some nodes remain unready for ever presumably due to
https://bugzilla.redhat.com/show_bug.cgi?id=1698253 which causes https://bugzilla.redhat.com/show_bug.cgi?id=1698624
Orthogonally some tests are timing out while the node eventually goes ready, hence this PR increases the polling time
See, all failures:
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/261/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/
e.g:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/261/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/781/
`ip-10-0-133-147.ec2.internal` makes `recover from deleted worker machines` to fail:
```E0412 08:06:15.948268    4971 …
```

Increase wait time for nodes going ready

---

pkg/e2e/operators/utils.go

This often takes a bit longer than the medium wait time.

e2e/operators/utils: Bump isDeploymentAvailable wait to long

---

pkg/e2e/operators/machine-api-operator.go

Accomodate for better controllers deployment naming https://github.com/openshift/machine-api-operator/pull/278 so it doesn't break the suite in any repo while the payload does not include #278

Accommodate for new deployment name: machine-api-controllers

---

Makefile
hack/ci-integration.sh

Operator behavior should be tested independently
from the functional behavior of the components
that the operators deploy.
The primary reason for this is to preserve logs
for troubleshooting test failures and flakes in
the functional tests.

Separate operators from functional test

---

hack/ci-integration.sh

So `make test-e2e` can be called over vendor test-suite as well.

Have ci-integration e2e workdir configurable

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/infra/infra.go

Relax the expected number of machineSets and replicas based on https://github.com/openshift/installer/issues/1698#issuecomment-488658119 and https://github.com/openshift/release/pull/3615 to temporary reduce CI cloud burden

Relax machineSets exepectations

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/autoscaler/counter.go
pkg/e2e/autoscaler/event.go
pkg/e2e/framework/framework.go

Scale out all machinesets at the same time. The previous
behaviour persisted with scaling one machine set at a time but we
want to validate across all available machine sets, in parallel.
This change also switches to using events to control test
termination. The intent is to implement the test using
cluster-autoscaler primitives and not use implementation
details (e.g., the replica count) on a scalable resource. We
have other e2e tests that validate the behaviour of
increasing/decreasing the replica count for low-level scaling.

e2e/autoscaler: scale out in parallel

---

pkg/e2e/autoscaler/autoscaler.go

Choose a time that is at least twice as the sync period
and that has high least common multiple to avoid a case
when a node is considered to be empty even if there are
pods already scheduled and running on the node.

Increase unneeded time to scale down a node

---

Makefile
pkg/e2e/machinehealthcheck/machinehealthcheck.go

- create separate make target for tech preview e2e tests
- skip tech preview tests under the test-e2e target
- skip tech preview tests under the k8s-e2e target

Introduce a separate target to run tech preview e2e tests

---

pkg/e2e/operators/cluster-autoscaler-operator.go
pkg/e2e/operators/utils.go

This adds two small tests to ensure that invalid ClusterAutoscaler and
MachineAutoscaler resources are rejected early by the validating
webhooks deployed by the cluster-autoscaler-operator.

pkg/e2e/operators: Add tests for rejecting invalid CAO resources

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go

It just takes longer and worker nodes have more resource capacity.

Increase workload and timeouts for Azure

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/framework/common.go
pkg/e2e/framework/framework.go
pkg/e2e/infra/infra.go
pkg/e2e/infra/utils.go

Rather than use the MachineSet's that may (or may not) come with the
installed platform we now create the number of MachineSet's we
actually need as part of test setup; on AWS we get three and on Azure
we currently get one. To handle these kind of differences this commit
changes the autoscaler and infra tests to create what it needs as part
of test setup.
The new setup requires at least one MachineSet with an accompanying
Node to be present. From that MachineSet we create the missing
MachineSet's - solely for autoscaler testing. Labels and the
ProviderSpec are propagated to the new MachineSet's from the first
MachineSet discovered on the cluster.

e2e: create required MachineSets as part of test setup

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/framework/common.go

This reverts the commit (in PR #96) that globally bumped the test timeouts. The intent in that PR was to make e2e run to completion on Azure. As some of the e2e x Azure issues have stabilised this reverts the global timeout changes but bumps localised cases in the autoscaler tests when scaling down. Nodes simply take longer to delete on Azure right now.

Reduce timeouts back to their previous default pre-Azure

---

Makefile

Once a spec in our e2e fails let's fail fast so we don't have to wait
a long time when herding PRs through CI.

Makefile: add -ginkgo.failFast to e2e invocations

---

Makefile
pkg/e2e/autoscaler/autoscaler.go

The autoscaler tests are most susceptible to the current state of the
cluster when they start running. If previous tests don't clean up
properly then we end up with additional nodes that will be used for
scheduling and that will break the expectations in the e2e/autoscaler
specs.
To mitigate the randomized ordering we now run the autoscaler tests
first by always specifying the _same_ seed value (so no more
randomized testing). It just so happens (I suspect) that "Autoscaler"
is now listed first due to sorting/collating. We should be wary of
this when adding new specs.
We will revisit this change once we have made further progress with
general test cleanup, particularly on any failure. Flaking on the
autoscaler tests is currently very costly as we have pushed out gating
time to 1h 45m …

Makefile: ensure e2e/autoscaler tests run first in test-e2e target

---

pkg/e2e/framework/common.go

As e2e tests are flaking/failing because their timeout is exceeded,
increasing `WaitLong` from 10min to 15min.
```console
I0807 04:10:42.570984    7150 utils.go:398] [0s remaining] Waiting for RC ready replicas, ReadyReplicas: 17, Replicas: 20
```

e2e/framework: Bump WaitLong from 10m to 15m

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/infra/infra.go

The combination of the MachineSet and Machine Name were busting GCP
limits for resource names which must be 1-63 characters in length[1].
I have manually tested the two cases where we using this auto
generated names and both cases now pass.
```console
• [SLOW TEST:737.138 seconds]
[Feature:Machines] Autoscaler should
/home/aim/go-projects/cluster-api-actuator-pkg/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go:231
scale up and down
/home/aim/go-projects/cluster-api-actuator-pkg/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go:232
SSSSS
Ran 1 of 16 Specs in 737.139 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 15 Skipped
PASS
```
```console
• [SLOW TEST:502.141 seconds] …
```

Use smaller names when creating transient MachineSets

---

pkg/e2e/infra/infra.go

Wait for a drained node to be deleted a bit longer (1m -> 3m)
Otherwise, the draining test is failing:
```
I0917 09:36:16.493790       1 controller.go:227] Machine "machine1" deletion successful
```
```
E0917 09:35:39.750590    6102 infra.go:464] Machine "machine1" not yet deleted
I0917 09:35:39.750938    6102 infra.go:365] Deleting object "pdb"
```
The machine deletion took 37s longer.

Wait for a drained node to be deleted a bit longer (1m -> 3m)

---

pkg/e2e/e2e_test.go
pkg/e2e/framework/common.go
pkg/e2e/framework/machinehealthcheck.go
pkg/e2e/framework/nodes.go
pkg/e2e/machinehealthcheck/machinehealthcheck.go

This (re)adds an E2E test suite and associated helpers to cover the MachineHealthCheck feature. This now works with version v1beta1 of the MachineHealthCheck API. The tests operate on a dedicated MachineSet, which should allow things to be paralellized more easily in the future.

e2e: Add MachineHealthCheck tests for v1beta1

---

Dockerfile
Makefile

This adds a Dockerfile so Prow can build an image containing the test suite.

Allow setting BUILD_DEST and add Dockerfile

---

pkg/e2e/framework/common.go
pkg/e2e/infra/infra.go

This is a cherry-pick of #124 to the release-4.2 branch. This adds a random ID to the machine names used in infra tests to avoid collisions.

[release-4.2] Bug 1776936: Add a random ID to machine names in infra tests

---

pkg/e2e/infra/infra.go

On Azure, by default we only get 2 CPUs for each machine. During some tests, we attempt to fit a minimum of 19 of these pods on a single node. Currently the azure e2e suite is failing because the 19th pod becomes unschedulable as there is not enough CPU allocatable on a single node. Given this used to work I'm assuming someone modified the default reservations for kubelet and system CPU at some point in the openshift installer
Reducing to 40m will hopefully mean they still spread evenly across nodes initially, but will fit on the single azure instance once the test is underway

[OCPCLOUD-765] Reduce test RC CPU to 40m

---

README.md

I've removed the instructions for running the tests against Minikube as these are out of date and do not work.
In their place I have added instructions for users to set up a cluster using IPI, disable CVO, deploy their test code (in the cluster or locally) and then have left the instructions at the bottom for the building and running the e2e tests that were there before

[OCPCLOUD-763] Update instructions for running e2e tests

---

pkg/e2e/framework/common.go
pkg/e2e/infra/infra.go

This prepends the cluster name, as found in the status of the global infrastructure object, to temporary machines created for e2e tests. This works around issues with the installer not tearing down resources that don't follow this naming scheme.
https://bugzilla.redhat.com/show_bug.cgi?id=1793051

e2e: Prepend cluster name to machines in infra tests

---

pkg/e2e/autoscaler/autoscaler.go
pkg/e2e/e2e_test.go
pkg/e2e/infra/infra.go
pkg/e2e/operators/cluster-autoscaler-operator.go
pkg/e2e/operators/machine-api-operator.go

Remove import aliases to make tests more readable.

Remove import aliases to make tests more readable

---

Makefile
hack/junitmerge.sh
pkg/e2e_test.go

This enables packages using this test suite to output JUnit reports for consumption by Prow, this will make it easier to interpret test failures within these tests
Adding `JUNIT_DIR=$ARTIFACTS` when running the test suite should result in this being picked up by Prow

[OCPCLOUD-789] Allow E2E suite to output JUnit files

---

Makefile

Actuator tests are currently broken [[example](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/550/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1892)] with the error:
```
Failed to compile pkg:
go test: mod flag may be set only once
run "go help test" or "go help testflag" for more information
```
This should fix that

Only add -mod=vendor when GOFLAGS not already set

---

pkg/framework/clusterautoscalers.go
pkg/framework/framework.go
pkg/framework/machines.go
pkg/framework/machinesets.go
pkg/framework/nodes.go

By wrapping these errors, we preserve the underlying API error types which allows the errors to be read by the [apimachinery errors](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/errors/errors.go) package. 
This allows tests to determine the cause of an error and act appropriately. Eg you can tell if a resource does not exist vs a connection timeout error.

Bug 1838523: Wrap API errors in framework

---

pkg/framework/machines.go
pkg/infra/infra.go
pkg/machinehealthcheck/machinehealthcheck.go

Ensure e2e test check recovery from all machines deletion

OCPCLOUD-439 - Make "recover from deleted worker machines" test more disruptive

---

pkg/autoscaler/autoscaler.go

This change switches the way the autoscaler tests calculate the usable
ram on worker nodes for the purpose of building resource requirements
for workload jobs. Prior to this commit, the tests have been using the
memory capacity of a node to determine the resource requirement. This
behavior can lead to failures in cases where the amount of actual
allocatable ram differs significantly from the capacity. This change
simply changes the calculation function to use the allocatable ram.

change autoscaler tests to use allocatable ram

---

pkg/autoscaler/autoscaler.go

The Autoscaler "scale up and down" test used these variables to record
information but these usages do not have direct bearing on the test.
Additionally the initial check of "nodes == machines" does not test the
scaling behavior and it will cause issues when attempting to parallelize
these tests.

remove existingMachines and existingNodes variables

---

pkg/autoscaler/autoscaler.go

This change adds a test to the autoscale "scale up and down" suite that
will check to see if there are any deletion annotations left on the
machine resources after a scale down. To accomplish this some logic has
been added to make the test wait until the scale down has completed so
that we can check the remaining machines.
This test is related to bugzilla case 1820410. reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1820410

add a test for deletion annotations after scale down

---

pkg/autoscaler/autoscaler.go

I've update two of the test cases that appeared to be flaky while I've been looking into the Azure E2E failures.
From what I can tell, it can sometimes take longer than expected to shut down machines based on which provider we are using.
The first test that I updated expected that the machine count and node count should be equal at the beginning of the test, while this may be true, I don't see any reason why we shouldn't give the test a moment to stabilise before starting, so now we give it a `WaitMedium` to allow the nodes/machines to fully shut down from previous tests before starting this one.
Eg:
- https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/167/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e-aws-operato …

Reduce flakiness of autoscaler tests

---

pkg/autoscaler/autoscaler.go
pkg/framework/machinesets.go

This change brings in a test for the --balance-similar-nodes option of the cluster autoscaler. It also includes a change which refactors the event watcher to be more common among the autoscaler tests.
The new test will create 2 MachineSets and then a workload which should demonstrate a balanced growth of those sets without reaching their maximum node sizes.
This change is dependent on #151

Test for balanced nodes

---

pkg/autoscaler/autoscaler.go

this change is minor, but it is fixing an incorrect label used for the
workloads in the balance nodes test.

change selector label name for balance nodes test

---

pkg/infra/mock/metadata_mock.go
pkg/infra/spot.go

This PR adds a new test to the spot tests that deploys a mock metadata service to the openshift cluster, and then intercepts traffic from one of the spot nodes to reroute traffic from the metadata service to the mock metadata service to trigger a termination event for the Machine. This should exercise that a termination handler is capable of shutting down a Machine if it receives a termination event.

[OCPCLOUD-901] Test spot termination handlers react to termination events

---

pkg/e2e_test.go
pkg/framework/framework.go

This PR extends the timeouts we set on our E2E tests for providers that are slower at starting and stopping machines.
Also includes the contents of #169 which I was trying to test separately (hoping it would pass on it's own accord)

Allow longer period for tests to pass on slower providers

---

pkg/infra/spot.go

This ensures that all outbound connections to the metadata service are looped back to localhost, this forces the traffic through the iptables rules set up earlier in this script, proxying the traffic to the fake metadata service

Loop metadata service connections to localhost

---

pkg/infra/spot.go

Allow Azure spot instances to be tested as part of the end to end suite

[OCPCLOUD-865] Add Azure support for spot instances tests

---

pkg/operators/machine-api-operator.go

I keep seeing the following in test failures, looks like we are checking the object before the error. Would be better to check the error first so that the error message is displayed in the JUnit output
```
/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/operators/machine-api-operator.go:129
Expected
<*v1.ValidatingWebhookConfiguration | 0x0>: nil
not to be nil
/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/operators/machine-api-operator.go:134
```
Secondly, based on some analysis of the test results, it looks like we are not actually waiting for the object to be deleted and recreated in the recover after deletion tests.
These are the only tests that should be deleting the MWC/VWC yet looking at the must-gather for …

Reduce failures in webhook tests

---

pkg/autoscaler/autoscaler.go

This test regularly flakes. This PR extends the timeout to wait for the nodes to go away so that slower providers have more time to remove the nodes. To fail early, this also introduces a check that the replicas of the MachineSet has been reduced to 1 before waiting for the nodes to go away. If this hasn't happened within the period we can skip waiting for the longer period for the nodes to go away as we know that won't happen.
Example output from a flake:
```
/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/autoscaler/autoscaler.go:521
Timed out after 360.000s.
Error: Unexpected non-nil/non-zero extra argument at index 1:
<*fmt.wrapError>: &fmt.wrapError{msg:"error getting node from machine \"ci-op-9i19wc9q-d57e2-t8sw7gx8g9-2l966\": nodes …
```

Wait on MachineSet replicas before waiting for nodes to go away

---

Makefile

We have disruptive tests in the operator suite that do not tolerate running in parallel. Disable the parallelism until we come up with a better way to run the tests in parallel. (This may not actually be possible given the types of objects we are working with)

Run operator tests in serial rather than parallel

---

pkg/infra/spot.go

This means that the test suite only needs to spin up a single machineset for spot instances.
This is an easy alternative to having a `BeforeAll` which will hopefully come in Ginkgo V2, once it does, we can revert this and change the `BeforeEach` to a `BeforeAll`.
My hope is that by reducing the number of spot instances we need to spin up, this will improve the reliability of this test on Azure which seems to have some issues bringing up spot instances.
I'd suggest reviewing this with white space changes ignored, it should make a lot more sense that way 🤞 
CC @kwoodson

Merge spot tests to a single test

---

pkg/infra/spot.go

To enable https://github.com/openshift/machine-api-operator/pull/627 to merge and allow the providers to migrate, we are going to need to temporarily disable the tests.
Merging the MAO changes first breaks the permissions for the service account and hence breaks the test. Merging the implementation first then doesn't have the appropriate permissions to set conditions on nodes, and breaks the tests.
Only with both merged can we re-enable the tests.

Temporarily skip tests to ease termination handler conditions migration

---

pkg/infra/webhooks.go

Reverts openshift/cluster-api-actuator-pkg#189
Webhooks changes have been merged, we should re-enable the validation to prove the webhooks are performing as expected

Re-enable webhook validation

---

Dockerfile.ci

This Dockerfile will build e2e tests in a separate image, which will be used to run in a dedicated CI step.
Built for https://github.com/openshift/ci-tools/blob/master/CONFIGURATION.md#images
This PR unblocks https://github.com/openshift/release/pull/13838

Bug 1880738: Add Dockerfile for CI step running mahcine-api e2e tests

---

pkg/autoscaler/autoscaler.go
pkg/framework/nodes.go

This is an attempt to improve the resilience of the following test. In this case, the node had gone away but the Machine had not. We can check those two things separately. The `GetNodesFromMachineSet` helper in the framework should be ignoring the not found error, it is up to the caller to check the number is correct.
```
Machine Suite: [Feature:Machines] Autoscaler should use a ClusterAutoscaler that has 12 maximum total nodes count and balance similar nodes enabled scales up and down while respecting MaxNodesTotal [Slow][Serial] expand_less | 23m20s
-- | --
/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/autoscaler/autoscaler.go:521 Timed out after 360.001s. Error: Unexpected non-nil/non-zero extra argument at index 1: 	<*fmt.wrapError>: &fmt.wrapError{msg:"error getting node …
```

Improve resilience of autoscaler 12 nodes total test

---

Makefile
pkg/framework/framework.go
pkg/operators/cluster-autoscaler-operator.go
pkg/operators/cluster-machine-approver.go
pkg/operators/machine-api-operator.go

Proxy tests are containing some basic post condition identifying cluster as recovered.

Bug 1913341: [OCPCLOUD-1072] Add Disruptive test selection and mark proxy tests as disruptive.

---

pkg/operators/machine-api-operator.go

This change adds the `P` prefix to the `It` clauses for the webhook
tests. This is being done temporarily to allow for MAO webhook
dependency changes to pass the test suite, then they will be revendored
into the test suite, at which point the tests will be re-enabled.
ref: https://github.com/openshift/machine-api-operator/pull/855

Bug 1954177: mark webhook tests as pending

---

pkg/operators/machine-api-operator.go

This change reverts the changes added in #210 to re-enable the webhook tests.

Bug 1954177: revert pending webhook tests

---

pkg/infra/spot.go

Reverts openshift/cluster-api-actuator-pkg#197 which disabled the termination handler tests to allow us to migrate from the deletion implementation to the conditions implementation

Bug 1914837: Re-enable termination handler tests

---

pkg/autoscaler/autoscaler.go
pkg/framework/framework.go

Based on the test results of #202, v1beta1 has been removed, and as such, this test is now perma-failing. Moving to v1 should resolve the issue.
```
E0712 08:41:39.099087   12407 framework.go:128] error querying api for ValidatingWebhookConfiguration: no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", retrying...
```

Bug 1986990: WaitForValidatingWebhook should use v1 instead of removed v1beta1

---

pkg/infra/spot.go

Spot tests are currently broken when the spot price is set to the empty string, let's not set the spot price if it's empty.
```
Machine error: failed to create machine "ci-op-xjhkjx76-d57e2-75kbmvgjwn-b85rl" scope: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'%!(EXTRA string=failed to get machine config)
```

Bug 1989051: Do not set spot max price if empty

---

pkg/infra/infra.go

We keep seeing tests using this replication controller fail because of image pull back off issues for the `busybox` image. This is likely because the docker hub image is being rate limited in CI.
eg The following error is consistent across all pods on [this CI run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-actuator-pkg/203/pull-ci-openshift-cluster-api-actuator-pkg-master-e2e-vsphere-operator/1457737345141837824)
```
"state": {
[10]           "waiting": {
[10]             "reason": "ImagePullBackOff",
[10]             "message": "Back-off pulling image \"busybox\""
[10]           }
[10]         },
```
By using a registry.ci image we won't have issues with pull limits in the future

Replace docker hub image with registry image in rc controller

---

pkg/infra/webhooks.go

Change minimal providerSpec for vSphere. All fields in vSphere's provider spec might be required depending on installation, we can leave only secret references empty.

Change minimal providerSpec for vSphere

---

pkg/operators/machine-api-operator.go

These tests modify the machine api controllers deployment and the mutating/validating webhook configurations. This means that they cannot be run in parallel with any tests that rely on these components. These tests disrupt the functionality of the cluster and must be run in serial to prevent flakes from other tests.

Mark MAO deployment tests as disruptive

---

pkg/autoscaler/autoscaler.go

This PR enables running autoscaler tests for Vsphere platfrom, since autoscaling from/to zero on Vsphere should be enabled by openshift/machine-api-operator#839.

Enable running autoscaler tests for Vsphere

---

Makefile
pkg/autoscaler/autoscaler.go
pkg/framework/jobs.go
pkg/infra/lifecyclehooks.go

Tests that pre-drain and pre-terminate hooks prevent pods being evicted and machine deleted respectively.

Add E2E test for Machine Deletion Hooks

---

pkg/infra/webhooks.go

We are going to make this field mandatore in the spec, so tests must specify it.

Bug 2060068: add security groups to the minimal AWS prover spec

---

pkg/e2e_test.go
pkg/infra/webhooks.go

Recently we have added webhooks for Power VS in mapio with the [PR](https://github.com/openshift/machine-api-operator/pull/998), So in this PR adding support for Power VS in Webhook tests

Bug 2097607: Add Powervs support for Webhook tests

---

pkg/autoscaler/autoscaler.go
pkg/e2e_test.go
pkg/infra/webhooks.go

After adding the Machine CR defaulter and validator webhooks for Nutanix platform (openshift/machine-api-operator repo PRs #1034, #1038), we need to add Nutanix as the supported platform in the "Webhooks" test cases of the cluster-api-actuator-pkg repo, for the e2e-nutanix-operator test run to pass.

Bug 2106403: Add Nutanix as the supported provider platform for e2e-nutanix-operator test

---

pkg/framework/framework.go
pkg/framework/machines.go
pkg/framework/machinesets.go

this change makes it so that any test using WaitForMachineSets will exit
if any of the machines come up in failed phase. it will print the failed
machines and exit the test.

add failed machine detection to WaitForMachineSets

---

pkg/framework/proxies.go
pkg/operators/machine-api-operator.go

This test is currently not working as expected (and also not failing?) as the mitm-proxy daemonset was being deployed to the default namespace.
If instead we deploy to our own namespace, we don't need to worry about the pod security admission policy and can fix the tests for the short term.
In the long term we will want to work out how to reduce these privileges and remove the need for the privileged namespace

Ensure proxy test pods run in privileged namespace

---

pkg/infra/infra.go

Policy v1beta1 stopped being served as a part of K8s 1.25.
This means this test is now failing since the 1.25 rebase landed.
This is blocking the tests from getting to the autoscaler tests

Migrate PDB to policy v1

---

pkg/operators/machine-api-operator.go

We are shortly going to introduce periodic tests for this test suite, and this test is the prime candidate for moving to periodic. I would like to disable it for now to reduce the likelihood of our test suites timing out (which we are seeing frequently on Azure).
This test takes upwards of 20 minutes to complete and because of its disruptive nature, cannot be run in parallel. It is very expensive to run on presubmits and it doesn't provide that much value to us. We haven't had any issues with the proxy configuration since it was set up some releases ago so I'm confident that disabling this for a few weeks won't cause an issue.
Periodics jira tracking: https://issues.redhat.com/browse/OCPCLOUD-1732

Disable proxy test until periodics are set up

---

pkg/infra/spot.go

The failure rate of this test has increased significantly on Azure and AWS. We are seeing a massive spike in not being able to create instances due to a lack of capacity on the platform. Skip the test until we have time to work out how to mitigate this.
In the future we will want to do something along the lines of:
* Try different instance types if we cannot get capacity
* Try different availability zones if we cannot get capacity
To make this easier, we should make sure that capacity failures appear on the status of Machines on both AWS and Azure.
Currently on AWS an error is logged as this is a 500 error, but it does not end up on the status. We will want to interpret the error and be smarter about reporting this condition.
Tracking card for re-enabling this test: …

Disable spot instance tests until further notice

---

pkg/autoscaler/autoscaler.go
pkg/framework/machinesets.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/providers/aws.go

@elmiko recently reported that he was seeing cordoned Machines interfering with tests in the autoscaler suite. When running the suite against a test cluster I observed that MachineSets were deleted but the suite moved onto new tests before the old Machines had gone away.
When writing tests we should always make sure we leave the environment clean _before_ we declare the test finished.
This PR adds ensures that every test we have that creates a MachineSet, has a `WaitForMachineSetsDeleted` call in an after each when the test finishes. This helper looks for Machines owned by the MachineSet and only finishes successfully once all of those Machines have gone away.
This should ensure we lave the Machine state clean after these tests.

Wait for Machines to be deleted before completeing each test case

---

Makefile
pkg/autoscaler/autoscaler.go
pkg/framework/framework.go
pkg/framework/jobs.go
pkg/framework/machinesets.go
pkg/framework/nodes.go

this change makes it so that the max nodes test will observe only the ready nodes in the cluster when determining if the maximum has been reached. the autoscaler will only count ready nodes when performing its calculations, when this is combined with tests that might not clean up the cluster properly, or may leave nodes in a non schedulable state, then the test need to take into account only the ready nodes when calculating the maximum size.
this PR also changes the workload job names that are run in the autoscaler tests to ensure that they are unique from each other.

update autoscaler max nodes test

---

Makefile
pkg/autoscaler/autoscaler.go
pkg/framework/framework.go
pkg/framework/jobs.go
pkg/framework/machines.go
pkg/framework/machinesets.go
pkg/framework/nodes.go
pkg/framework/proxies.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/operators/machine-api-operator.go
pkg/providers/aws.go

This PR backports various improvements to the package back into `release-4.11`.

OCPCLOUD-1757: release-4.11, backport various improvements

---

Makefile
pkg/autoscaler/autoscaler.go
pkg/e2e_test.go
pkg/framework/framework.go
pkg/framework/jobs.go
pkg/framework/machines.go
pkg/framework/machinesets.go
pkg/framework/nodes.go
pkg/framework/pods.go
pkg/framework/proxies.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/mock/metadata_mock.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/operators/machine-api-operator.go

This PR backports various improvements to the package back into `release-4.10`.
3 notable changes that differ from a plain cherry-pick of all commits:
1) [backport: pkg/infra cleanup](https://github.com/openshift/cluster-api-actuator-pkg/commit/127c62689438075f34c917ac5054a0bbcb35be1e) is a squashed and fixed up version of:
```
backport: pkg/infra cleanup
A fixup of 4 commits plus
removal of unndeded aws IMDSv2 tests (feature not present on 4.10) from backport
| * https://github.com/openshift/cluster-api-actuator-pkg/commit/38d03aac8b59e9d75b967eae0a5bf1c0f4ef7aa6 update error construction in GetPlatform func (6 months ago) <Denis Moiseev>
| * https://github.com/openshift/cluster-api-actuator-pkg/commit/82e156081765425ce523749f373d577bcba3edf0 Fix broken spot tests, rename helper, small …
```

OCPCLOUD-1757: release-4.10, backport various improvements

---

Makefile
OWNERS
pkg/autoscaler/autoscaler.go
pkg/e2e_test.go
pkg/framework/framework.go
pkg/framework/jobs.go
pkg/framework/machinehealthcheck.go
pkg/framework/machines.go
pkg/framework/machinesets.go
pkg/framework/nodes.go
pkg/framework/pods.go
pkg/framework/proxies.go
pkg/framework/webhooks.go
pkg/infra/infra.go
pkg/infra/mock/metadata_mock.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/machinehealthcheck/machinehealthcheck.go
pkg/operators/machine-api-operator.go

This PR backports various improvements to the package back into release-4.9.
Some notable changes that differ from a plain cherry-pick of all commits:
1) [[4.9 backport] machinev1 to machinev1beta1 changes](https://github.com/openshift/cluster-api-actuator-pkg/commit/2fcfd35138eca51750e82b8e5a8784a8fee0016b)
Modified version of the original:
- Migrate tests to openshift/api from MAO - https://github.com/openshift/cluster-api-actuator-pkg/commit/2be3519893eabd08780b5d96649e2d051d1166b9
to use the new import names
but keep the old import api path local to the repository, for easier
merge conflict handling.
2) [backport: pkg/infra cleanup](https://github.com/openshift/cluster-api-actuator-pkg/commit/127c62689438075f34c917ac5054a0bbcb35be1e) is a squashed and fixed up version of:
``` …
```

OCPCLOUD-1757: release-4.9, backport various improvements

---

pkg/framework/jobs.go

There are rate limits for dockerhub, which causes tests to fail.
https://github.com/openshift/machine-api-operator/pull/1082 - vsphere-operator job here, for example

Replace busybox image from dockerhub with ubi-minimal from RH registry

---

.ci-operator.yaml
.gitignore
pkg/autoscaler/autoscaler.go
pkg/framework/framework.go
pkg/framework/gatherer/data-gatherer.go
pkg/framework/gatherer/oc-cli.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/machinehealthcheck/machinehealthcheck.go
pkg/operators/cluster-autoscaler-operator.go
pkg/operators/machine-api-operator.go
pkg/providers/aws.go

This adds a gatherer helper for dumping resources and pod logs for failed tests.
This PR contains:
- tiny wrapper around `oc` CLI, which allows to leverage oc binary for retrieving resources and pod logs
- `StateGatherer` helper, which provides shortcuts for dump MAPI related resources and pod logs
- enables gathering for failed tests across the suite
- (also, .ci-operator.yaml was added, just by the way )
Notes:
* This thing relies on `oc` presence within PATH. In CI this requires `oc` to be injected https://docs.ci.openshift.org/docs/architecture/step-registry/#injecting-the-oc-cli

OCPCLOUD-1711: Resources and logs gatherer for failed tests

---

Makefile
pkg/operators/machine-api-operator.go

This PR adds a target to run e2e periodic tests only.

[OCPCLOUD-1732] Add test-e2e-periodic target in the makefile

---

Makefile
pkg/framework/machinesets.go
pkg/infra/spot.go

This PR rewrites machineSet setup logic for spot test to allow it to detect when one of the machines cannot scale up due to insufficient spot capacity. If that happens, then it gets deleted, and it attempts again with a new machineSet that has a different instance type. 
This is attempted 3 times. If it cannot scale after that, the test fails.

OCPCLOUD-1733: Try alternative instance type when spot has no capacity

---

pkg/autoscaler/autoscaler.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/machinehealthcheck/machinehealthcheck.go
pkg/operators/machine-api-operator.go
pkg/providers/aws.go

This PR reduces the amount of machine creation to the minimum that is required. 
- It moves the "scales up and down while respecting MaxNodesTotal [Slow][Serial]" test own context. Reducing MaxNodesTotal from 12 to 8. Also adds Eventualy for "Ensuring there are 6 machines in the cluster" at the beginning of the test. I hope that this will reduce the flakiness of this test.
- Infra test are grouped into 'When("machineset has x replicas")' contexts that set up the initial machine set replica count
Tests with changes:
1. "have ability to additively reconcile taints from machine to nodes" 2 -> 1 machine
2. In "grow and decrease when scaling different machineSets simultaneously" reduces machineset2 to 2 replicas from 3
3. "reject invalid machinesets" 2 -> 0 replicas by not using shared setup …

OCPCLOUD-1743 Reduce amount of machines creation

---

pkg/infra/spot.go

The logic that tries different machineSets when the instance type does not have spot capacity did not remove the old machineSet, but waited for that mahineSet to be deleted. This caused the spot test to fail when there was insufficient capacity for the first instance type it tried.
> MachineSet ci-op-fvk1klgj-efb8d-sn7ndxr57k still exists and does not have a deletion timestamp
This PR adds the missing call to delete the machineSet.

Fix spot test alternative machineset logic

---

pkg/providers/aws.go

The curl command is sometimes missing http status header in verbose mode. I am not sure why this happens, but the IMDS works correctly, as seen by it printing correct ami. I hope that this change will make the test more stable by requesting it to print only the status code.
```
[FAILED] Expected
<string>: [21 bytes data]
100    21  100    21    0     0  21000      0 --:--:-- --:--:-- --:--:-- 21000
* Closing connection 0
ami-0e95030500ad17daa
to contain substring
<string>: HTTP/1.1 200 OK
```

Make IMDS test more stable

---

testutils/resourcebuilder/machine/v1beta1/machine.go

This can be used in unit testing where you aren't using a client, but passing Machine objects around. Need for CPMS testing since I'm moving the API call higher up the stack.

Add WithDeletionTimestamp to MachineBuilder

---

pkg/operators/cluster-autoscaler-operator.go
pkg/operators/cluster-machine-approver.go
pkg/operators/machine-api-operator.go

The exception statements `Except`, `Eventually`, and `Consistently` should have annotations associated with them so that debugging test failures is easier.

OCPCLOUD-1716: Add annotations to exceptions in operators pkg

---

pkg/autoscaler/autoscaler.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/machinehealthcheck/machinehealthcheck.go
pkg/providers/aws.go

There were several issues, the more serious one was a problem where cleanup would wipe all existing machinesets (the existing ones, before the tests ran) when the tests were skipped.
Moving the cleanup code to a `DeferCleanup()` function fixes it.

OCPBUGS-9925: Fix tests for OpenStack platform

---

pkg/autoscaler/autoscaler.go
pkg/framework/machinesets.go

This PR sets `machine.openshift.io/cluster-api-machineset` label on machineset to enable testing of availabilitySet feature on Azure.

OCPBUGS-25940: Exercise availabilitySets in E2E

---

pkg/autoscaler/autoscaler.go

Hello,
another bug fix for [OCPBUGS-33974](https://issues.redhat.com/browse/OCPBUGS-33974). :)
[This PR](https://github.com/openshift/cluster-api-actuator-pkg/pull/317) was intended as a change to some ScaleFromZero E2E tests that were causing periodics on all platforms to fail - but I didn't remove the check for the deprecated GPU annotation and the new upstream GpuCount/GpuType annotations. This means the periodics for platforms that do not include the GPU annotations by default when opting in to autoscaling were still having their periodics failing. 
Another PR to fix this, and some refactoring based on [some feedback from Joel on the first PR](https://github.com/openshift/cluster-api-actuator-pkg/pull/317#discussion_r1615864941).
Thanks!

OCPBUGS-33974: Remove checking for GPU annotations in ScaleFromZero E2E tests

---

testutils/matchers.go
testutils/matchers_test.go

This adds a new gomega matcher called `MatchViaJSON` that converts objects to JSON before using the gomega `MatchJSON` matcher.
This matcher is useful when structs contain maps that you do not necessarily care about the ordering for. For example, when we are converting machines between mapi and capi and we care about the content of the map, not the order, this matcher can successfully match objects, without the need for the order to be exactly correct.

Add MatchViaJSON matcher to testutils

---

testutils/resourcebuilder/coalesce.go
testutils/resourcebuilder/machine/v1beta1/aws_provider_spec.go
testutils/resourcebuilder/machine/v1beta1/aws_provider_spec_test.go
testutils/resourcebuilder/machine/v1beta1/coalesce.go
testutils/resourcebuilder/machine/v1beta1/machine.go
testutils/resourcebuilder/machine/v1beta1/machine_test.go
testutils/resourcebuilder/machine/v1beta1/machineset.go
testutils/resourcebuilder/machine/v1beta1/machineset_test.go
testutils/resourcebuilder/machine/v1beta1/suite_test.go

extend fields of resourcebuilder to allow for more flexibility for the following:
- testutils: resourcebuilder: machinev1beta1.AWSProviderSpec extend fields
- testutils: resourcebuilder: machinev1beta1.Machine extend fields
- testutils: resourcebuilder: machinev1beta1.MachineSet extend fields
**Testing**:
To prove this doesn't break existing use cases I ran cluster-control-plane-machine-set-operator unit tests successfully.
```
Ginkgo ran 11 suites in 5m30.502007958s
Test Suite Passed
```

OCPCLOUD-2749: testutils: resourcebuilder: extend fields

---

pkg/autoscaler/autoscaler.go

This change updated the error messages and extends the timeout for the deletion cleanup test to improve the behavior.

NOJIRA: adding more logging to deletion taint cleanup test

---

pkg/providers/aws.go

Based on https://redhat-internal.slack.com/archives/CBUT43E94/p1732621241891359, PGE have blocked us from being able to create capacity reservations on the fly. So for now, we need to disable this to unblock CI across the board.
CC @huali9 I think this may impact your QE env tests, but I'm not sure how to make this skip on one env, but not the other.
Do you know if there's a flag somewhere that we could use within the test suite to know that we are on the QE env?

Disable capacity reservation test until further notice

---

Makefile
pkg/autoscaler/autoscaler.go
pkg/framework/ginkgo-labels.go
pkg/infra/infra.go
pkg/infra/lifecyclehooks.go
pkg/infra/spot.go
pkg/infra/webhooks.go
pkg/machinehealthcheck/machinehealthcheck.go
pkg/operators/cluster-autoscaler-operator.go
pkg/operators/cluster-machine-approver.go
pkg/operators/machine-api-operator.go
pkg/providers/aws.go

Update labels based on [doc](https://docs.google.com/document/d/1bMY03y2L7IFd2tYYo2RJNoX1ONPh88U2GslkFXYw8b8/edit?tab=t.0#heading=h.z2f5gniht7oe ) 
- QE run test in 2 jobs, one is non-disruptive, one is disruptive, so added disruptive labels to some cases to make sure these cases are not run in parallel.
- In order to select feature related cases in different repos, added capi/mapi/autoscaler/machine-health-checks/machine-approver/ccm labels.
- Added qe-only/dev-only label to make sure some cases can only run in qe or dev account.
- I didn't update Makefile to `LEVEL0&&!qe-only` as now only few LEVEL0 cases, and we have a total of 41 cases in repo, so I think keep the status quo is ok, in future we have more cases, then we change it to run only LEVEL0. If you think it's better to change …

OCPQE-26161,OCPBUGS-46552: Update labels to distinguish different tests

---

pkg/capi/aws.go
pkg/framework/aws_client.go

As the resources we pre-created are deleted, so we have to update this case to create and delete the resources in the automation, run in local passed. @sunzhaohua2 @miyadav @shellyyang1989 @JoelSpeed PTAL, thanks!
```
liuhuali@Lius-MacBook-Pro cluster-api-actuator-pkg % ./hack/ci-integration.sh -focus "should be able to run a machine using KMS keys" -v
Running Suite: Machine Suite - /Users/liuhuali/project/cluster-api-actuator-pkg/pkg
===================================================================================
Random Seed: 1735027225
Will run 1 of 45 specs
[BeforeSuite] 
/Users/liuhuali/project/cluster-api-actuator-pkg/pkg/e2e_test.go:63
[BeforeSuite] PASSED [1.425 seconds]
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
```

OCPQE-27644: upd75396

---

testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go

To avoid duplicating this logic in cluster-capi-operator.
While here, we also alphabetise the parameters and (most) helpers.

OSASINFRA-3689: Add additional OpenStack test helpers

---

testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go

We want to be able to create fake ports also.
This is a follow-up to https://github.com/openshift/cluster-api-actuator-pkg/pull/371

OSASINFRA-3689: Add yet more OpenStack helpers

---

testutils/resourcebuilder/machine/v1beta1/gcp_provider_spec.go

This change updates the gcp provider spec builder to allow setting of disks. It retains the current default.

Adds ability to set disks to gcp provider builder

---

testutils/resourcebuilder/machine/v1beta1/gcp_provider_spec.go

This change updates the gcp provider spec builder to allow setting of project ids. It retains the current default.

Adds ability to set project to gcp provider builder

---

hack/ci-integration.sh
pkg/framework/framework.go
pkg/framework/machinesets.go
pkg/infra/spot.go
pkg/infra/webhooks.go

Fixed some issues found in qe ci jobs, @huali9 @miyadav @shellyyang1989 PTAL
- When one case failed, other cases will be interrupted, set `--fail-fast=false` so that other cases can be tested.
- Spot case failed on arm clusters, add instance types for arm clusters
- Update GetArchitectureFromMachineSetNodes to get arch from annotation
- Skip spot case on customer vpc clusters, as error:
```
termination-simulator-p862v                           1/1     Running   0              31s
$ oc logs -f termination-simulator-p862v          
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: network error (check Internet connection and firewall)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No …
```

OCPQE-27285: Fix the failures in qe ci jobs

---

testutils/resourcebuilder/cluster-api/infrastructure/v1beta1/openstackmachine.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta1/openstackmachine_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta1/openstackmachinetemplate.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta1/openstackmachinetemplate_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/powervsmachine.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/powervsmachine_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/powervsmachinetemplate.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/powervsmachinetemplate_test.go

Adds ownerReference to resource builders for InfraMachines and InfraMachineTemplates.

OCPCLOUD-2716: add ownerReference to resource builders

---

testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine_test.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate.go
testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate_test.go

Adds new field networkInterfaceType to awsMachine and awsMachineTemplate resource builders.

OCPCLOUD-2895: Add networkInterfaceType to AWS builders

---

pkg/capi/azure.go

Same with https://github.com/openshift/cluster-capi-operator/pull/276
https://github.com/openshift/installer/pull/9538 introduced some changes in how MAPZ machines get generated.
So we need to account for it when we generate the CAPZ machine from those.
@huali9 @miyadav PTAL
```
$ ./hack/ci-integration.sh -focus "Cluster API Azure MachineSet should be able to run a machine" -v
Running Suite: Machine Suite - /Users/sunzhaohua/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg
=========================================================================================================
Random Seed: 1744346690
Will run 1 of 59 specs
[BeforeSuite] 
/Users/sunzhaohua/go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e_test.go:68
[BeforeSuite] PASSED …
```

OCPQE-27285: azure coditionally set identity

---

pkg/capi/aws.go
pkg/capi/azure.go
pkg/capi/core.go

auto [OCP-75779 - [CAPI] Labels and annotations specified in a machineset should propagate to nodes](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-75779)
passed on AWS, Azure and GCP. @sunzhaohua2 @miyadav @shellyyang1989 PTAL, thanks!
On AWS
```
liuhuali@Lius-MacBook-Pro cluster-api-actuator-pkg % ./hack/ci-integration.sh -focus "Cluster API MachineSet" -v
Running Suite: Machine Suite - /Users/liuhuali/project/cluster-api-actuator-pkg/pkg
===================================================================================
Random Seed: 1744627579
Will run 1 of 63 specs
[BeforeSuite] 
/Users/liuhuali/project/cluster-api-actuator-pkg/pkg/e2e_test.go:68
[BeforeSuite] PASSED [1.371 seconds] …
```

OCPQE-29297: auto75779

---

pkg/autoscaler/autoscaler.go

this change makes the timeout 15 minutes for the autoscaler test where we scale out to maximum size. on some platforms, it appears that 5 minutes is not enough time.

increase the timeout for scaling out

---

pkg/framework/machinesets.go

Add authoritativeAPI for MachineSetParams so that can change authoritativeAPI for migration testing.

OCPCLOUD-2555: Add authoritativeAPI for MachineSetParams

---

pkg/framework/capi_machinesets.go

Create capi machineset in region without zones, report below error, this try to fix this issue.
```
Expected success, but got an error:
<*errors.StatusError | 0xc000a13cc0>: 
MachineSet.cluster.x-k8s.io "azure-machineset-75884" is invalid: spec.template.spec.failureDomain: Invalid value: "": spec.template.spec.failureDomain in body should be at least 1 chars long
```
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-api-provider-azure/335/pull-ci-openshift-cluster-api-provider-azure-master-regression-clusterinfra-azure-ipi-techpreview/1922992711938347008

NO-JIRA: fix no failureDomain failure in azure

---

pkg/operators/machine-api-operator.go

[It] When cluster-wide proxy is configured, Machine API cluster operator should create machines when configured behind a proxy
There are many jobs in qe ci, but this case failed on disconnected jobs when DeployProxy, because the url cannot be accessed on disconnected cluster, so I'd like to mark this case only run in dev env.
@sunzhaohua2 @miyadav @shellyyang1989 PTAL, thanks!

OCPQE-27646: add label for the proxy case

---

pkg/framework/ginkgo-labels.go
pkg/operators/machine-api-operator.go

Refer https://github.com/openshift/cluster-api-actuator-pkg/pull/353#issuecomment-2948288605, but I checked the code of dynamically checking if it's a disconnected cluster, it's complicated and time consuming, so I prefer to use label
@sunzhaohua2 @miyadav @shellyyang1989 PTAL, thanks!

OCPQE-27646: addlabel2

---

pkg/annotations/gcp.go
pkg/e2e_test.go
pkg/framework/gcp_client.go

Adding annotation tests on gcp . This is work in progress , any suggestions are welcome.

OCPQE-27708 - Annotationtestsgcp

---

testutils/resourcebuilder/machine/v1beta1/azure_provider_spec.go

This adds an image option to the Azure resourcebuilder for use in https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/368

NO-ISSUE: Add image option to Azure resourcebuilder

---

pkg/framework/capi_machinesets.go

Fixes flake where deletion succeeded but racy due to eventually and trying a gain to delete:
```
STEP: Deleting MachineSet "aws-machineset-76794" - /go/src/github.com/openshift/cluster-api-actuator-pkg/pkg/framework/capi_machinesets.go:122 @ 09/17/25 15:18:19.147
[FAILED] Timed out after 900.001s.
the CAPI MachineSets should have been deleted
Expected success, but got an error:
<*errors.StatusError | 0xc000d1a8c0>: 
machinesets.cluster.x-k8s.io "aws-machineset-76794" not found
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "machinesets.cluster.x-k8s.io \"aws-machineset-76794\" not found",
Reason: "NotFound",
Details: {
Name: "aws-machineset-76794",
Group: …
```

NO-JIRA: framework: fix flake on deleting machinesets
